layout_spectrum: 1
typography_spectrum: 0
color:
  saturation: 0.02150538
  lightness: 0.8333333
  brandStrength: 0.2580645
  rhythmicContrast: 0.3494624
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: tiinateaspoon
